#ifndef __AUTO_VERSION_HEADER
#define __AUTO_VERSION_HEADER

#define VERSION_MAJOR_RELEASE		0
#define VERSION_MINOR_RELEASE		6
#define VERSION_EXTERNAL_BUILD		0
#define VERSION_INTERNAL_BUILD		0

#define VERSION_STRING				"0, 6, 0, 0"
#define VERSION_STRING_DOTTED		"0.6.0.0"

#endif // __AUTO_VERSION_HEADER
